### ISSUE TITLE
Concerning the suitability of NFT and FT traits as example contracts

### ISSUE THREAD

**Issue by mefrem** [hirosystems/clarity-examples#6]
I'm concerned that providing the SIP-009 or SIP-010 traits as example contracts will encourage their publication to the blockchain. These contracts specify the NFT and FT traits. They are not, in and of themselves, NFT collections or new fungible tokens. (Furthermore, it's not best practice to publish the same contract logic to the chain multiple times, given the original contracts can be referenced.)

I think a better NFT (or FT) contract example would be one that 1) implements the SIP-009 trait, and 2) declares a new NFT collection, prompting the user who imports/clones this example contract to rename it (and customize it further to the user's liking).

**Comment by sabbyanandan** [comment]
Addressed via https://github.com/hirosystems/clarity-examples/pull/8.
